- .travis.yml
- lib/regexp_parser/scanner/scanner.rl
- test/scanner/test_groups.rb
Ruby allows specifying zero length group comments (as in `/foo(?#)bar/`).
See: #11
> Fix lexing for zero length group comment `/(?#)/`

- lib/regexp_parser/syntax/ruby/1.9.1.rb
- lib/regexp_parser/syntax/tokens/escape.rb
- test/parser/test_escapes.rb
- test/syntax/ruby/test_1.9.1.rb
* Adds support to 1.9 syntax
* Adds regression test for parsing
* Adds test asserting that ruby 1.9 supports this syntax
Fixes #13
> Fix parse of escape:codepoint_list

- lib/regexp_parser/syntax/ruby/1.9.1.rb
- lib/regexp_parser/syntax/tokens/escape.rb
- test/parser/test_escapes.rb
A previous commit (9803fb2) fixed improper parsing of `/\h/` but unintentionally dropped support for multibyte hex escapes.
> Fix parsing of /\xFF/n (hex:escape)

- README.md
- Rakefile
- bin/test
- lib/regexp_parser/scanner/property.rl
- lib/regexp_parser/scanner/scanner.rl
- lib/regexp_parser/token.rb
- test/expression/test_base.rb
- test/expression/test_conditionals.rb
- test/lexer/test_conditionals.rb
- test/parser/test_quantifiers.rb
- test/parser/test_sets.rb
- test/scanner/test_escapes.rb
- test/support/disable_autotest.rb
- test/support/runner.rb
- test/support/warning_extractor.rb
- test/syntax/ruby/test_1.9.3.rb
- test/warnings.yml
This PR eliminates all avoidable errors emitted at runtime. It also adds a custom test runner that builds on top of `test/unit`. This runner loads a warning whitelist (`test/warnings.yml`) and asserts that the test suite does not emit any other warnings.
> Remove warnings

- lib/regexp_parser/scanner/scanner.rl
- lib/regexp_parser/syntax/tokens/escape.rb
- test/parser/test_escapes.rb
- test/scanner/test_escapes.rb
- test/warnings.yml
Hi,
I’ve made a small gem based on regexp_parser. It’s called [js_regex](https://github.com/janosch-x/js_regex). Nothing special, but it might cause most of regexp_parser’s usage now, as it has turned into a dependency of the fairly popular [client_side_validations](https://github.com/DavyJonesLocker/client_side_validations) gem.
Either way, I have found a few minor things and will open some PRs or issues for them these days.
Here is the first:
Regexp::Scanner won’t accept wide codepoints (or "codepoint lists", which I’ve never seen used as such) with a length other than 4.
E.g.:
```ruby
/\u{41}/ =~ 'A' # => 0
Regexp::Scanner.scan(/\u{41}/) # => Regexp::Scanner::ScannerError: Scan error at '\u{41}'
```
The most common use case for this might be scanning for astral plane chars (?).
```ruby …
```
> Improve codepoint handling

- lib/regexp_parser/scanner/property.rl
- test/parser/test_properties.rb
- test/scanner/test_properties.rb
- test/scanner/test_sets.rb
See issue #28.
The `in_set` global is actually set correctly [here](https://github.com/ammar/regexp_parser/blob/2e9cda515a4f03952d7f444407d617d747bb3c5e/lib/regexp_parser/scanner/property.rl#L63), but for nonproperties with a caret, the `:set` type is then overridden [here](https://github.com/ammar/regexp_parser/blob/2e9cda515a4f03952d7f444407d617d747bb3c5e/lib/regexp_parser/scanner/property.rl#L70-L72).
This PR fixes this.
As a bonus, it correctly detects `\P{^foo}` as a positive `:property`, although probably no one in his right mind would write that 😁
> Make property scanning in sets consistent

- lib/regexp_parser/syntax/tokens/character_set.rb
- test/parser/test_sets.rb
- test/scanner/test_sets.rb
```ruby
Regexp::Parser.parse(/[\x20-\x28]/)
Regexp::Parser.parse(/[\x20]/)
```
> Fix NotImplementedError for 'member_hex' tokens

- lib/regexp_parser/syntax/ruby/1.9.1.rb
- lib/regexp_parser/syntax/tokens/escape.rb
- test/parser/test_escapes.rb
- test/syntax/ruby/test_1.9.1.rb
This fixes the following:
```ruby
Regexp::Parser.parse(/a\177b/)
```
In truth, the `octal` escape is available since at least Ruby 1.8.6, but this is also true for the `hex` escape and possibly more token types in the 1.9.1 syntax file, and I didn't want to mess with that.
> Fix NotImplementedError for octal escapes

- lib/regexp_parser/expression/classes/type.rb
- lib/regexp_parser/parser.rb
- lib/regexp_parser/scanner/scanner.rl
- lib/regexp_parser/syntax/ruby/2.0.0.rb
- lib/regexp_parser/syntax/tokens/character_set.rb
- lib/regexp_parser/syntax/tokens/character_type.rb
- test/parser/test_types.rb
- test/scanner/test_sets.rb
- test/scanner/test_types.rb
`\R` seems to be useful mainly to deal with the occasional Windows linebreak:
```ruby
"___\r\n___\n___".gsub(/\R/, 'x') # => "___x___x___"
```
`\X` is for [extended graphemes](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries), e.g. latin letters with combined diacritical marks:
```ruby
'g̈'.scan(/./) # => ["g", "̈"]
'g̈'.scan(/\X/) # => ["g̈"]
```
They were added with Onigmo. Relevant documentation is [here](https://github.com/k-takata/Onigmo/blob/fc16bafc139016a7d5d8098efadcd97e749d3523/doc/RE#L109-L124).
> Add support for linebreak and extended grapheme types ("\R" and "\X")

- lib/regexp_parser/parser.rb
- lib/regexp_parser/scanner/scanner.rl
- test/parser/test_escapes.rb
- test/scanner/test_errors.rb
- test/scanner/test_escapes.rb
- test/warnings.yml
So far, regexp_parser only supports this style:
```ruby
"\M-\C-A" # => "\x81"
```
Ruby provides these other styles as well:
```ruby
"\M-\cA"  # => "\x81"
"\C-\M-A" # => "\x81"
"\c\M-A"  # => "\x81"
```
These are currently scanned and/or parsed incorrectly, e.g.:
```ruby
Regexp::Parser.parse(/\C-\M-A/n).expressions
```
> Add support for more metacontrol notations

- lib/regexp_parser/scanner/scanner.rl
- test/warnings.yml
Current version of this gem emits a Ruby warning even only when being required:
```sh
% ruby -rregexp_parser -wep
.../gems/regexp_parser-1.2.0/lib/regexp_parser/scanner.rb:1146: warning: assigned but unused variable - testEof
```
Now we're seeing this error everyday, in my case probably because capybara is depending on this gem.
I know this patch is a dirty solution, but this eliminates the warning anyway.
> Eliminate "warning: assigned but unused variable - testEof"

- regexp_parser.gemspec
This reduces unneeded redirection from `http://...` to `https://...` when someone visits this gem's homepage via https://rubygems.org/gems/regexp_parser.
> GitHub is HTTPS by default

- lib/regexp_parser/expression/methods/match_length.rb
- lib/regexp_parser/expression/methods/traverse.rb
- spec/expression/methods/match_length_spec.rb
- spec/expression/methods/traverse_spec.rb
Currently, `Subexpression#traverse` and `Subexpression#each_expression` require a block. 
So It is difficult to combine other Enumerator methods, such as `map`, `select` and so on.
```ruby
require 'regexp_parser'
root = Regexp::Parser.parse(/foo|bar/)
result = []
root.each_expression do |expr|
result << expr if expr.is_a?(Regexp::Expression::Literal)
end
p result
result = root.each_expression.select do |expr, _idx|
expr.is_a?(Regexp::Expression::Literal)
end
p result
```
And, in the real world, I'd like to use it for RuboCop.
https://github.com/pocke/rubocop-regular_expression/blob/b3f243b01973705cf43e8a3594c0854729e1ab7d/lib/rubocop/cop/regular_expression/mixed_capture_types.rb#L31-L41
Make them accept calling without a block.
I found a bug of `MatchLength#each` method. It wasn't aware …
> Make traverse/each_expression to return an Enumerator if they're called without a block

- README.md
- lib/regexp_parser/scanner/scanner.rl
- spec/lexer/delimiters_spec.rb
- spec/parser/quantifiers_spec.rb
- spec/scanner/delimiters_spec.rb
- spec/scanner/errors_spec.rb
Interprets the `{`, `}`, and `]` delimiters as literals depending on the context.
_Notes_
- Reduce ambiguity in the `quantifier_interval` pattern by replacing the optional matchers with 4 fixed patterns.
- Remove the `premature_end_error` final state handler from `quantifier_interval` to permit valid literal sequences.
Closes #63
> Support informal delimiter literals

- README.md
- lib/regexp_parser/lexer.rb
- lib/regexp_parser/parser.rb
- lib/regexp_parser/scanner/scanner.rl
- spec/parser/options_spec.rb
- spec/scanner/options_spec.rb
@jaynetics as mentioned in https://github.com/rubocop-hq/rubocop/pull/8625#issuecomment-691471124 - please let me know what you think 👍
> Allow options to be passed when processing a String pattern

- lib/regexp_parser/expression.rb
Ranges are frozen by default in Ruby 3 which prevents patching in minmax here- since the issue this patch works around was fixed in Ruby 2.7 don't patch where not needed.
> Don't modify range for Ruby 2.7+

- CHANGELOG.md
- lib/regexp_parser/expression/classes/group.rb
- lib/regexp_parser/expression/quantifier.rb
- lib/regexp_parser/parser.rb
- spec/expression/to_s_spec.rb
- spec/parser/quantifiers_spec.rb
- spec/scanner/quantifiers_spec.rb
@ammar wanna take a look?
this adds support for chained quantifiers by wrapping their targets in passive groups.
it modifies the node tree while parsing, similar to the treatment of alternations, ranges in sets etc.
this seems to be the most pragmatic way to handle these edge cases. existing integrations of the gem will keep working without effort, and if someone really wants to treat these cases in a special way, they can check `#implicit?`.
i also explored some other approaches, which seemed worse:
1. allowing `Quantifier` objects to have a `#quantifier` themselves
- this would mirror Onigmo, where quantifiers are normal nodes and can thus have a quantifier (via a pointer)
- this is bad IMO because it hides the problem: people will not usually check this method and existing …
> Add simple handling/workaround for chained quantifiers

- Rakefile
- lib/regexp_parser/expression/classes/free_space.rb
- lib/regexp_parser/expression/methods/match_length.rb
- lib/regexp_parser/expression/methods/traverse.rb
- lib/regexp_parser/syntax/any.rb
- spec/expression/subexpression_spec.rb
- spec/parser/errors_spec.rb
- spec/parser/quantifiers_spec.rb
I noticed there was an unused variable in the quantifier spec when I was trying to find a spot to write tests for #77. I think it was meant to be used as an assertion so I added it in the first commit here.
Since I noticed that unused variable by chance, I decided to run `rubocop --lint` and found a few other minor issues that felt like they might be worth a quick fixup. Feel free to reject these changes or I can drop commits you don't like but I thought they were all small improvements.
You might consider adding a minimal `rubocop` config with some basic linting and such enabled to avoid small items like these if you like these changes. If you don't, that's fine too.
> Misc. cleanup

- Gemfile
- lib/regexp_parser/expression/classes/group.rb
- spec/expression/to_s_spec.rb
- spec/spec_helper.rb
On [mutant](https://github.com/mbj/mutant) we aggressively freeze objects and work with immutable structures. In trying to [re-introduce support](https://github.com/mbj/mutant/pull/1166) for (immutably) mutating regular expressions I ran into an issue with the 2.x series of `regexp_parser` that prevented calling `#to_s` on frozen passive groups. The change I am having trouble with was introduced [here](https://github.com/ammar/regexp_parser/commit/f14a36bff6fef3ef174b63c744c556469a42a589#diff-5bfe3942df5a59a97d7e5c7d3e918a1c704f964685e719c178af22401da46c23R25).
I am proposing a simple fix here that should hopefully not impact anything else but does allow calling `#to_s` on a frozen passive group.
@jaynetics could you let me know what you think about this issue/approach? Thanks again with …
> Support `#to_s` on frozen Group::Passive

- .github/workflows/tests.yml
This PR just adds Ruby 3.0 to the CI test matrix.
> Add Ruby 3.0 to CI matrix

- regexp_parser.gemspec
As a pupular gem, `regexp_parser` implicitly requires that all
privileged operations by any of the owners require OTP.
However, by explicitly setting `rubygems_mfa_required` metadata, the
gem will show "NEW VERSIONS REQUIRE MFA" and
"VERSION PUBLISHED WITH MFA" in the sidebar at
https://github.com/ammar/regexp_parser
Ref:
- https://blog.rubygems.org/2022/08/15/requiring-mfa-on-popular-gems.html
- https://guides.rubygems.org/mfa-requirement-opt-in/
> Opt-in for MFA requirement explicitly

- lib/regexp_parser/scanner/scanner.rl
- spec/scanner/groups_spec.rb
Previously, positive lookbehinds that contained literal `<` characters were erroneously tokenized as named groups instead of assertions. This fixes that to ensure that lookbehinds are treated as assertions.
This bug affects rubocop: https://github.com/rubocop/rubocop/issues/13511
Fixes #93.
> Update scanner.rl to not treat lookbehinds with literal `<` characters as named groups
